services:
  ewm-service:
    build: ./main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=localAdmin
      - SPRING_DATASOURCE_PASSWORD=localadmin
      - TZ=UTC

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=localAdmin
      - POSTGRES_PASSWORD=localadmin
      - TZ=UTC
    volumes:
      - ./main-service/src/main/resources:/docker-entrypoint-initdb.d

  stats-server:
    build: ./stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=localAdmin
      - SPRING_DATASOURCE_PASSWORD=localadmin
      - TZ=UTC

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=localAdmin
      - POSTGRES_PASSWORD=localadmin
      - TZ=UTC
    volumes:
      - ./stats-service/stats-server/src/main/resources:/docker-entrypoint-initdb.d