server:
  port: 0

grpc:
  server:
    port: 0

spring:
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: aggregator-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.practicum.aggregator.deserializer.UserActionDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.aggregator.serializer.AvroSerializer
      acks: all
      retries: 3
    poll:
      timeout: 1000

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    ru.practicum: DEBUG
    org.apache.kafka: INFO